import React from 'react'

import { Space, mainTheme as theme } from '../theme'
import { transitions, Transition } from '../theme/timing'

import { Box } from '.'
import { ConstrainedBoxProps } from '..'

type LoaderProps = {
  size?: number
  duration?: number
} & ConstrainedBoxProps

export const Loader: React.FC<LoaderProps> = ({
  size = 'elephant',
  duration = 'giraffe',
  color,
  ...props
}) => {
  size = theme.space[size as Space]
  const sizePx = `${size}px`

  return (
    <Box role="alert" aria-busy="true" color={color} {...props}>
      {/* <!-- [ldio] generated by https://loading.io/ --> */}
      <svg
        xmlns="http://www.w3.org/2000/svg"
        style={{ shapeRendering: 'auto' }}
        width={sizePx}
        height={sizePx}
        viewBox={`0 0 100 100`}
        preserveAspectRatio="xMidYMid"
      >
        <path
          d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50"
          fill="currentColor"
          stroke="none"
        >
          <animateTransform
            attributeName="transform"
            type="rotate"
            dur={transitions[duration as Transition] as string}
            repeatCount="indefinite"
            keyTimes="0;1"
            values="0 50 51;360 50 51"
          ></animateTransform>
        </path>
      </svg>
    </Box>
  )
}
