on: [push, pull_request]
name: Build and maybe Publish
jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: 14.x-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install deps
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build

  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
    steps:
    - uses: actions/checkout@v2
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: 14.x-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install deps
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Get package version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Publish package
      id: publish
      uses: pascalgn/npm-publish-action@1.3.8
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 

    - name: Tag package if version is changed
      if: steps.publish.outputs.type != 'none'
      run: git tag ${{ steps.package-version.outputs.current-version}} && git push --tags
